// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAa-268Fx-XfJTsJLGznwcztd82r2vdf3Q',
    appId: '1:744810618140:web:1b333167538cf6d957aed9',
    messagingSenderId: '744810618140',
    projectId: 'marketsafe-e57cf',
    authDomain: 'marketsafe-e57cf.firebaseapp.com',
    storageBucket: 'marketsafe-e57cf.firebasestorage.app',
    measurementId: 'G-V85PLZFBZQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjSEtJ3f3FXdCrGj6BgrWkW-7_EID2JXk',
    appId: '1:744810618140:android:21734dc6e84b9eea57aed9',
    messagingSenderId: '744810618140',
    projectId: 'marketsafe-e57cf',
    storageBucket: 'marketsafe-e57cf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdZMZMQ1X1oVdQ5-aefVoLUWBbAhr_Rns',
    appId: '1:744810618140:ios:a46feedae992ee9357aed9',
    messagingSenderId: '744810618140',
    projectId: 'marketsafe-e57cf',
    storageBucket: 'marketsafe-e57cf.firebasestorage.app',
    iosBundleId: 'com.example.capstone2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdZMZMQ1X1oVdQ5-aefVoLUWBbAhr_Rns',
    appId: '1:744810618140:ios:a46feedae992ee9357aed9',
    messagingSenderId: '744810618140',
    projectId: 'marketsafe-e57cf',
    storageBucket: 'marketsafe-e57cf.firebasestorage.app',
    iosBundleId: 'com.example.capstone2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAa-268Fx-XfJTsJLGznwcztd82r2vdf3Q',
    appId: '1:744810618140:web:edfe2a3aebac75e157aed9',
    messagingSenderId: '744810618140',
    projectId: 'marketsafe-e57cf',
    authDomain: 'marketsafe-e57cf.firebaseapp.com',
    storageBucket: 'marketsafe-e57cf.firebasestorage.app',
    measurementId: 'G-0CQNLTWSR2',
  );

}